
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CB COMMA COMMENT CP EOL FUNC IDENT OB OPprogram : funcsfuncs : func funcsfuncs : func : FUNC IDENT OP params CP OB bodies CBbodies : bodyparams : IDENT paramsparams : IDENT COMMA paramsparams : body : IDENT OP CP bodiesbody : IDENT OP params CP bodiesbody : '
    
_lr_action_items = {'$end':([0,1,2,3,5,19,],[-3,0,-1,-3,-2,-4,]),'FUNC':([0,3,19,],[4,4,-4,]),'IDENT':([4,7,8,11,14,18,20,23,],[6,8,8,8,15,8,15,15,]),'OP':([6,15,],[7,18,]),'CP':([7,8,9,10,11,13,18,21,],[-8,-8,12,-6,-8,-7,20,23,]),'COMMA':([8,],[11,]),'OB':([12,],[14,]),'CB':([14,16,17,20,22,23,24,],[-11,19,-5,-11,-9,-11,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'funcs':([0,3,],[2,5,]),'func':([0,3,],[3,3,]),'params':([7,8,11,18,],[9,10,13,21,]),'bodies':([14,20,23,],[16,22,24,]),'body':([14,20,23,],[17,17,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> funcs','program',1,'p_program','lang.py',70),
  ('funcs -> func funcs','funcs',2,'p_funcs','lang.py',74),
  ('funcs -> <empty>','funcs',0,'p_funcs_empty','lang.py',78),
  ('func -> FUNC IDENT OP params CP OB bodies CB','func',8,'p_func','lang.py',82),
  ('bodies -> body','bodies',1,'p_bodies','lang.py',94),
  ('params -> IDENT params','params',2,'p_params','lang.py',98),
  ('params -> IDENT COMMA params','params',3,'p_params_many','lang.py',104),
  ('params -> <empty>','params',0,'p_params_empty','lang.py',109),
  ('body -> IDENT OP CP bodies','body',4,'p_body_','lang.py',113),
  ('body -> IDENT OP params CP bodies','body',5,'p_body_params','lang.py',119),
  ('body -> <empty>','body',0,'p_body_empty','lang.py',126),
]
